-- MariaDB baseline schema for Covers by Mobile Zam Zam.
--
-- GENERATED by scripts/hostinger/generate-schema.mjs from db/migrations.
-- Do not hand-edit: regenerate, review the diff, and commit.
--
-- Source D1 migrations : 0000_init.sql, 0001_installation_singleton.sql, 0002_two_factor_verification.sql, 0003_staff_invitations.sql, 0004_account_issuer.sql, 0005_product_search.sql, 0006_product_reviews.sql
-- Tables               : 101
-- Indexes              : 154
-- Foreign keys         : 106
--
-- Two departures from a literal translation, both deliberate:
--
--   * 4 SQLite partial unique indexes have no MariaDB equivalent and are
--     replaced by generated scope columns with an ordinary UNIQUE index over
--     them. See scripts/hostinger/lib/emit-mariadb.mjs for why a plain nullable
--     composite UNIQUE would enforce nothing.
--       product_specifications_variant_unique
--       product_specifications_product_unique
--       product_compatibility_variant_unique
--       product_compatibility_product_unique
--
--   * The FTS5 virtual table and its triggers are not translated. Search is a
--     materialised document table with a FULLTEXT index; see 0002_search.sql.
--
-- Every table is InnoDB and utf8mb4. Timestamps are epoch milliseconds in
-- BIGINT, stored UTC, displayed Europe/Rome by the application — the database
-- holds no timezone and no DATETIME, exactly as D1 did.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

-- ── Tables ──────────────────────────────────────────────────────────────
CREATE TABLE `account` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `account_id` VARCHAR(64) NOT NULL,
  `provider_id` VARCHAR(64) NOT NULL,
  `access_token` TEXT,
  `refresh_token` TEXT,
  `access_token_expires_at` BIGINT,
  `refresh_token_expires_at` BIGINT,
  `scope` VARCHAR(500),
  `id_token` TEXT,
  `password` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `issuer` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `permissions` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `role_permissions` (
  `id` VARCHAR(64) NOT NULL,
  `role_id` VARCHAR(64) NOT NULL,
  `permission_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `roles` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `is_system` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `session` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` BIGINT NOT NULL,
  `ip_address` VARCHAR(45),
  `user_agent` VARCHAR(500),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `staff_profiles` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL,
  `job_title` VARCHAR(255),
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_login_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  `suspended_at` BIGINT,
  `suspended_by` VARCHAR(255),
  `suspended_reason` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `step_up_sessions` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `purpose` VARCHAR(255) NOT NULL,
  `expires_at` BIGINT NOT NULL,
  `consumed_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `two_factor` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `secret` VARCHAR(500) NOT NULL,
  `backup_codes` TEXT,
  `verified` TINYINT(1) NOT NULL DEFAULT 0,
  `failed_verification_count` INT NOT NULL DEFAULT 0,
  `locked_until` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `image` VARCHAR(255),
  `two_factor_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_roles` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NOT NULL,
  `role_id` VARCHAR(64) NOT NULL,
  `granted_by` VARCHAR(255),
  `granted_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `verification` (
  `id` VARCHAR(64) NOT NULL,
  `identifier` VARCHAR(255) NOT NULL,
  `value` VARCHAR(500) NOT NULL,
  `expires_at` BIGINT NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `brand_translations` (
  `id` VARCHAR(64) NOT NULL,
  `brand_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `brands` (
  `id` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `logo_key` VARCHAR(255),
  `website_url` VARCHAR(255),
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `categories` (
  `id` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `parent_id` VARCHAR(64),
  `path` VARCHAR(255) NOT NULL,
  `depth` INT NOT NULL DEFAULT 0,
  `accessory_type` VARCHAR(255),
  `image_key` VARCHAR(512),
  `sort_order` INT NOT NULL DEFAULT 0,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `category_translations` (
  `id` VARCHAR(64) NOT NULL,
  `category_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `seo_title` VARCHAR(255),
  `seo_description` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_category_assignments` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `category_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_images` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64),
  `object_key` VARCHAR(512) NOT NULL,
  `alt_it` VARCHAR(500),
  `alt_en` VARCHAR(500),
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `file_size` INT NOT NULL,
  `file_hash` VARCHAR(128) NOT NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_relationships` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `related_product_id` VARCHAR(64) NOT NULL,
  `relationship_type` VARCHAR(64) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_safety_information` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `manufacturer_name` VARCHAR(255),
  `manufacturer_address` VARCHAR(255),
  `manufacturer_contact` VARCHAR(255),
  `product_identifier` VARCHAR(255),
  `responsible_person_name` VARCHAR(255),
  `responsible_person_address` VARCHAR(255),
  `responsible_person_contact` VARCHAR(255),
  `warnings_it` VARCHAR(255),
  `warnings_en` VARCHAR(255),
  `manual_url` VARCHAR(255),
  `recall_notice` VARCHAR(255),
  `disposal_info_it` VARCHAR(255),
  `disposal_info_en` VARCHAR(255),
  `certification` VARCHAR(255),
  `battery_notes` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_specifications` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64),
  `spec_key` VARCHAR(64) NOT NULL,
  `value_text` VARCHAR(255),
  `value_number` INT,
  `value_bool` INT,
  `unit` VARCHAR(255),
  `sort_order` INT NOT NULL DEFAULT 0,
  `variant_scope` VARCHAR(64) AS (COALESCE(`variant_id`, '')) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_specifications_scope_not_empty` CHECK (`variant_id` IS NULL OR `variant_id` <> '')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_translations` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `short_description` TEXT,
  `full_description` TEXT,
  `seo_title` VARCHAR(255),
  `seo_description` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_variants` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `sku` VARCHAR(64) NOT NULL,
  `barcode` VARCHAR(64),
  `variant_label` VARCHAR(255),
  `colour` VARCHAR(255),
  `length_mm` INT,
  `capacity_mah` INT,
  `connector` VARCHAR(255),
  `pack_size` INT NOT NULL DEFAULT 1,
  `weight_grams` INT,
  `dimensions_mm` VARCHAR(255),
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `available_online` TINYINT(1) NOT NULL DEFAULT 1,
  `available_for_pickup` TINYINT(1) NOT NULL DEFAULT 1,
  `allow_backorder` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `products` (
  `id` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `brand_id` VARCHAR(64),
  `primary_category_id` VARCHAR(64),
  `accessory_type` VARCHAR(255),
  `product_family_id` VARCHAR(64),
  `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
  `is_new` TINYINT(1) NOT NULL DEFAULT 0,
  `is_bestseller` TINYINT(1) NOT NULL DEFAULT 0,
  `published_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `variant_option_assignments` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `option_value_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `variant_option_groups` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `variant_option_values` (
  `id` VARCHAR(64) NOT NULL,
  `group_id` VARCHAR(64) NOT NULL,
  `value` TEXT NOT NULL,
  `label_it` VARCHAR(255) NOT NULL,
  `label_en` VARCHAR(255) NOT NULL,
  `swatch_hex` VARCHAR(255),
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `compatibility_verification_logs` (
  `id` VARCHAR(64) NOT NULL,
  `compatibility_id` VARCHAR(64) NOT NULL,
  `previous_level` VARCHAR(255),
  `new_level` VARCHAR(255) NOT NULL,
  `previous_verified` INT,
  `new_verified` INT NOT NULL,
  `source` VARCHAR(255),
  `note` TEXT,
  `changed_by` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_aliases` (
  `id` VARCHAR(64) NOT NULL,
  `device_model_id` VARCHAR(64) NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `alias_normalised` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_brand_translations` (
  `id` VARCHAR(64) NOT NULL,
  `device_brand_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_brands` (
  `id` VARCHAR(64) NOT NULL,
  `handle` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `logo_key` VARCHAR(255),
  `sort_order` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_families` (
  `id` VARCHAR(64) NOT NULL,
  `device_brand_id` VARCHAR(64) NOT NULL,
  `handle` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `release_year` INT,
  `sort_order` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_family_translations` (
  `id` VARCHAR(64) NOT NULL,
  `device_family_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_model_translations` (
  `id` VARCHAR(64) NOT NULL,
  `device_model_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `display_name` VARCHAR(255),
  `notes` TEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `device_models` (
  `id` VARCHAR(64) NOT NULL,
  `device_brand_id` VARCHAR(64) NOT NULL,
  `device_family_id` VARCHAR(64) NOT NULL,
  `handle` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `release_year` INT,
  `image_key` VARCHAR(512),
  `connector` VARCHAR(255),
  `is_popular` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_compatibility` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64),
  `device_model_id` VARCHAR(64) NOT NULL,
  `compatibility_level` VARCHAR(255) NOT NULL,
  `note` TEXT,
  `verified` TINYINT(1) NOT NULL DEFAULT 0,
  `verification_source` VARCHAR(255),
  `verified_by` VARCHAR(255),
  `verified_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `variant_scope` VARCHAR(64) AS (COALESCE(`variant_id`, '')) STORED,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_compatibility_scope_not_empty` CHECK (`variant_id` IS NULL OR `variant_id` <> '')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_families` (
  `id` VARCHAR(64) NOT NULL,
  `handle` VARCHAR(64) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_family_members` (
  `id` VARCHAR(64) NOT NULL,
  `product_family_id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `coupon_redemptions` (
  `id` VARCHAR(64) NOT NULL,
  `coupon_id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `customer_email` VARCHAR(255),
  `amount_discounted` INT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `coupons` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `discount_type` VARCHAR(255) NOT NULL,
  `discount_value` INT NOT NULL,
  `usage_limit` INT,
  `usage_count` INT NOT NULL DEFAULT 0,
  `per_customer_limit` INT,
  `starts_at` BIGINT NOT NULL,
  `ends_at` BIGINT,
  `min_order_amount` BIGINT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `price_history` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `price_list_id` VARCHAR(64) NOT NULL,
  `old_amount` BIGINT,
  `new_amount` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `channel` VARCHAR(255) NOT NULL,
  `effective_from` BIGINT NOT NULL,
  `effective_to` INT,
  `reason` VARCHAR(500),
  `changed_by` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `price_lists` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `channel` VARCHAR(255) NOT NULL,
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `promotion_products` (
  `id` VARCHAR(64) NOT NULL,
  `promotion_id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64),
  `variant_id` VARCHAR(64),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `promotions` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `discount_type` VARCHAR(255) NOT NULL,
  `discount_value` INT NOT NULL,
  `channel` VARCHAR(255) NOT NULL DEFAULT 'online',
  `starts_at` BIGINT NOT NULL,
  `ends_at` BIGINT,
  `priority` INT NOT NULL DEFAULT 0,
  `stackable` TINYINT(1) NOT NULL DEFAULT 0,
  `min_quantity` INT,
  `min_order_amount` BIGINT,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `variant_prices` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `price_list_id` VARCHAR(64) NOT NULL,
  `amount` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `prior_price_30d` INT,
  `prior_price_reference_date` INT,
  `cost_price` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `inventory_levels` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `location_id` VARCHAR(64) NOT NULL,
  `on_hand` INT NOT NULL DEFAULT 0,
  `reserved` INT NOT NULL DEFAULT 0,
  `incoming` INT NOT NULL DEFAULT 0,
  `reorder_threshold` INT,
  `allow_backorder` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `inventory_levels_reserved_bounds` CHECK (`reserved` >= 0 AND `reserved` <= `on_hand`),
  CONSTRAINT `inventory_levels_on_hand_non_negative` CHECK (`on_hand` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `inventory_locations` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `location_type` VARCHAR(255) NOT NULL,
  `sellable_online` TINYINT(1) NOT NULL DEFAULT 0,
  `sellable_in_store` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_adjustments` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `location_id` VARCHAR(64) NOT NULL,
  `quantity_before` INT NOT NULL,
  `quantity_after` INT NOT NULL,
  `reason_code` VARCHAR(255) NOT NULL,
  `reason_note` VARCHAR(255) NOT NULL,
  `performed_by` VARCHAR(255) NOT NULL,
  `movement_id` VARCHAR(64),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_movements` (
  `id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `location_id` VARCHAR(64) NOT NULL,
  `movement_type` VARCHAR(255) NOT NULL,
  `quantity_delta` INT NOT NULL,
  `quantity_before` INT NOT NULL,
  `quantity_after` INT NOT NULL,
  `reference_type` VARCHAR(64),
  `reference_id` VARCHAR(64),
  `reason` VARCHAR(500),
  `performed_by` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_reservations` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `location_id` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'active',
  `expires_at` BIGINT NOT NULL,
  `released_at` BIGINT,
  `released_reason` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_transfer_items` (
  `id` VARCHAR(64) NOT NULL,
  `transfer_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `quantity_sent` INT NOT NULL,
  `quantity_received` INT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `stock_transfers` (
  `id` VARCHAR(64) NOT NULL,
  `reference` VARCHAR(255) NOT NULL,
  `from_location_id` VARCHAR(64) NOT NULL,
  `to_location_id` VARCHAR(64) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'draft',
  `note` TEXT,
  `created_by` VARCHAR(255) NOT NULL,
  `received_by` VARCHAR(255),
  `received_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cart_items` (
  `id` VARCHAR(64) NOT NULL,
  `cart_id` VARCHAR(64) NOT NULL,
  `variant_id` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  `compatibility_at_add` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `carts` (
  `id` VARCHAR(64) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(64),
  `device_model_id` VARCHAR(64),
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `expires_at` BIGINT NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_addresses` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `address_type` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `street_number` VARCHAR(255),
  `postcode` VARCHAR(20) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `province` VARCHAR(2),
  `country` VARCHAR(2) NOT NULL DEFAULT 'IT',
  `phone` VARCHAR(40),
  `note` TEXT,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_events` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `event_type` VARCHAR(255) NOT NULL,
  `payload` MEDIUMTEXT,
  `customer_visible` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_items` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64),
  `variant_id` VARCHAR(64),
  `product_name` VARCHAR(255) NOT NULL,
  `variant_label` VARCHAR(255),
  `sku` VARCHAR(255) NOT NULL,
  `image_key` VARCHAR(512),
  `compatibility_state` VARCHAR(255),
  `device_model_name` VARCHAR(255),
  `quantity` INT NOT NULL,
  `unit_price` BIGINT NOT NULL,
  `discount_amount` BIGINT NOT NULL DEFAULT 0,
  `tax_amount` BIGINT NOT NULL DEFAULT 0,
  `line_total` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_notes` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `body` MEDIUMTEXT NOT NULL,
  `customer_visible` TINYINT(1) NOT NULL DEFAULT 0,
  `author_id` VARCHAR(64),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_status_history` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `from_status` VARCHAR(255),
  `to_status` VARCHAR(255) NOT NULL,
  `reason` VARCHAR(500),
  `actor` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` VARCHAR(64) NOT NULL,
  `order_number` VARCHAR(255) NOT NULL,
  `tracking_token` VARCHAR(128) NOT NULL,
  `user_id` VARCHAR(64),
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `customer_first_name` VARCHAR(255) NOT NULL,
  `customer_last_name` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  `customer_phone` VARCHAR(40),
  `customer_whatsapp` VARCHAR(255),
  `delivery_method` VARCHAR(255) NOT NULL,
  `shipping_method_id` VARCHAR(64),
  `pickup_location_id` VARCHAR(64),
  `payment_method_id` VARCHAR(64),
  `device_model_id` VARCHAR(64),
  `item_subtotal` BIGINT NOT NULL,
  `discount_total` BIGINT NOT NULL DEFAULT 0,
  `shipping_total` BIGINT NOT NULL DEFAULT 0,
  `tax_total` BIGINT NOT NULL DEFAULT 0,
  `grand_total` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `customer_note` TEXT,
  `terms_version_id` VARCHAR(64),
  `reservation_expires_at` BIGINT,
  `placed_at` BIGINT,
  `cancelled_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_payments` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `payment_method_id` VARCHAR(64) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'awaiting_customer_contact',
  `amount_expected` INT NOT NULL,
  `amount_claimed` INT,
  `amount_received` INT,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `transaction_reference` VARCHAR(255),
  `verified_by` VARCHAR(255),
  `verified_at` BIGINT,
  `verification_note` VARCHAR(255),
  `rejected_reason` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_methods` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `method_type` VARCHAR(255) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `description_it` VARCHAR(255),
  `description_en` VARCHAR(255),
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `beneficiary_name` VARCHAR(255),
  `account_identifier_encrypted` VARCHAR(255),
  `account_identifier_masked` VARCHAR(255),
  `merchant_qr_key` VARCHAR(255),
  `instructions_it` TEXT,
  `instructions_en` TEXT,
  `staff_instructions` VARCHAR(255),
  `reservation_minutes` INT NOT NULL DEFAULT 1440,
  `eligible_for_shipping` TINYINT(1) NOT NULL DEFAULT 1,
  `eligible_for_pickup` TINYINT(1) NOT NULL DEFAULT 1,
  `min_amount` BIGINT,
  `max_amount` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_proof_access_logs` (
  `id` VARCHAR(64) NOT NULL,
  `proof_id` VARCHAR(64) NOT NULL,
  `accessed_by` VARCHAR(255) NOT NULL,
  `accessed_at` BIGINT NOT NULL,
  `ip_address` VARCHAR(45),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_proofs` (
  `id` VARCHAR(64) NOT NULL,
  `order_payment_id` VARCHAR(64) NOT NULL,
  `object_key` VARCHAR(512) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `file_size` INT NOT NULL,
  `original_filename_display` VARCHAR(255),
  `uploaded_at` BIGINT NOT NULL,
  `uploaded_by_ip` VARCHAR(255),
  `deleted_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payment_status_history` (
  `id` VARCHAR(64) NOT NULL,
  `order_payment_id` VARCHAR(64) NOT NULL,
  `from_status` VARCHAR(255),
  `to_status` VARCHAR(255) NOT NULL,
  `amount_at_transition` INT,
  `reason` VARCHAR(500),
  `actor` VARCHAR(255) NOT NULL,
  `is_correction` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fulfilment_items` (
  `id` VARCHAR(64) NOT NULL,
  `fulfilment_id` VARCHAR(64) NOT NULL,
  `order_item_id` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fulfilment_status_history` (
  `id` VARCHAR(64) NOT NULL,
  `fulfilment_id` VARCHAR(64) NOT NULL,
  `from_status` VARCHAR(255),
  `to_status` VARCHAR(255) NOT NULL,
  `reason` VARCHAR(500),
  `actor` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `fulfilments` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `fulfilment_type` VARCHAR(255) NOT NULL,
  `location_id` VARCHAR(64),
  `prepared_by` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pickup_orders` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `location_id` VARCHAR(64) NOT NULL,
  `ready_at` BIGINT,
  `ready_by` VARCHAR(255),
  `collected_at` BIGINT,
  `collected_by` VARCHAR(255),
  `collected_by_name` VARCHAR(255),
  `pickup_deadline` INT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `refund_items` (
  `id` VARCHAR(64) NOT NULL,
  `refund_id` VARCHAR(64) NOT NULL,
  `order_item_id` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  `amount` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `refunds` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `return_request_id` VARCHAR(64),
  `amount` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `refund_method` VARCHAR(255) NOT NULL,
  `reference` VARCHAR(255),
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `processed_by` VARCHAR(255),
  `processed_at` BIGINT,
  `note` TEXT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `return_items` (
  `id` VARCHAR(64) NOT NULL,
  `return_request_id` VARCHAR(64) NOT NULL,
  `order_item_id` VARCHAR(64) NOT NULL,
  `quantity` INT NOT NULL,
  `condition_code` VARCHAR(255),
  `inspection_note` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `return_requests` (
  `id` VARCHAR(64) NOT NULL,
  `order_id` VARCHAR(64) NOT NULL,
  `reference` VARCHAR(255) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'requested',
  `reason_code` VARCHAR(255) NOT NULL,
  `reason_note` VARCHAR(255),
  `is_withdrawal` TINYINT(1) NOT NULL DEFAULT 0,
  `requested_at` BIGINT NOT NULL,
  `approved_by` VARCHAR(255),
  `approved_at` BIGINT,
  `received_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipments` (
  `id` VARCHAR(64) NOT NULL,
  `fulfilment_id` VARCHAR(64) NOT NULL,
  `carrier_name` VARCHAR(255),
  `tracking_number` VARCHAR(255),
  `tracking_url` VARCHAR(255),
  `shipped_at` BIGINT,
  `delivered_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipping_methods` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `description_it` VARCHAR(255),
  `description_en` VARCHAR(255),
  `rate_type` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `dispatch_note_it` VARCHAR(255),
  `dispatch_note_en` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipping_rates` (
  `id` VARCHAR(64) NOT NULL,
  `shipping_method_id` VARCHAR(64) NOT NULL,
  `shipping_zone_id` VARCHAR(64) NOT NULL,
  `amount` BIGINT NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `free_over_amount` BIGINT,
  `min_weight_grams` INT,
  `max_weight_grams` INT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shipping_zones` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `countries` VARCHAR(255) NOT NULL,
  `postcode_prefixes` VARCHAR(255),
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `banners` (
  `id` VARCHAR(64) NOT NULL,
  `placement` VARCHAR(255) NOT NULL,
  `message_it` VARCHAR(255) NOT NULL,
  `message_en` VARCHAR(255) NOT NULL,
  `link_url` VARCHAR(255),
  `image_key` VARCHAR(512),
  `starts_at` BIGINT,
  `ends_at` BIGINT,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `homepage_section_translations` (
  `id` VARCHAR(64) NOT NULL,
  `section_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `heading` VARCHAR(255),
  `subheading` VARCHAR(255),
  `body_text` VARCHAR(255),
  `cta_label` VARCHAR(255),
  `cta_url` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `homepage_sections` (
  `id` VARCHAR(64) NOT NULL,
  `section_type` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `config` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `legal_document_versions` (
  `id` VARCHAR(64) NOT NULL,
  `document_id` VARCHAR(64) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  `body_it` MEDIUMTEXT,
  `body_en` MEDIUMTEXT,
  `effective_from` BIGINT NOT NULL,
  `published_at` BIGINT,
  `published_by` VARCHAR(255),
  `reviewed_by_lawyer` TINYINT(1) NOT NULL DEFAULT 0,
  `review_note` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `legal_documents` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name_it` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `current_version_id` VARCHAR(64),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `navigation_items` (
  `id` VARCHAR(64) NOT NULL,
  `menu_id` VARCHAR(64) NOT NULL,
  `parent_id` VARCHAR(64),
  `label_it` VARCHAR(255) NOT NULL,
  `label_en` VARCHAR(255) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `icon_name` VARCHAR(255),
  `depth` INT NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `navigation_menus` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `page_translations` (
  `id` VARCHAR(64) NOT NULL,
  `page_id` VARCHAR(64) NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `excerpt` VARCHAR(255),
  `body` MEDIUMTEXT,
  `seo_title` VARCHAR(255),
  `seo_description` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pages` (
  `id` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'draft',
  `publish_at` BIGINT,
  `page_type` VARCHAR(255) NOT NULL DEFAULT 'page',
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `archived_at` BIGINT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `store_settings` (
  `id` VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `value` TEXT NOT NULL,
  `value_type` VARCHAR(255) NOT NULL DEFAULT 'string',
  `category` VARCHAR(255) NOT NULL,
  `description_it` VARCHAR(255),
  `gates_feature` TINYINT(1) NOT NULL DEFAULT 0,
  `is_sensitive` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `audit_logs` (
  `id` VARCHAR(64) NOT NULL,
  `actor_id` VARCHAR(64) NOT NULL,
  `actor_label` VARCHAR(255),
  `action` VARCHAR(255) NOT NULL,
  `entity_type` VARCHAR(64) NOT NULL,
  `entity_id` VARCHAR(64) NOT NULL,
  `before_value` VARCHAR(255),
  `after_value` VARCHAR(255),
  `request_id` VARCHAR(64),
  `ip_address` VARCHAR(45),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `email_logs` (
  `id` VARCHAR(64) NOT NULL,
  `outbox_event_id` VARCHAR(64),
  `recipient` VARCHAR(255) NOT NULL,
  `template` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `status` VARCHAR(64) NOT NULL,
  `provider_message_id` VARCHAR(64),
  `error` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `export_jobs` (
  `id` VARCHAR(64) NOT NULL,
  `export_type` VARCHAR(255) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `result_object_key` VARCHAR(255),
  `row_count` INT,
  `filters` VARCHAR(255),
  `created_by` VARCHAR(255) NOT NULL,
  `completed_at` BIGINT,
  `expires_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `feature_flags` (
  `id` VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `idempotency_keys` (
  `id` VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `scope` VARCHAR(255) NOT NULL,
  `owner_token` VARCHAR(255),
  `result_payload` MEDIUMTEXT,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `expires_at` BIGINT NOT NULL,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `import_job_rows` (
  `id` VARCHAR(64) NOT NULL,
  `import_job_id` VARCHAR(64) NOT NULL,
  `row_number` INT NOT NULL,
  `outcome` VARCHAR(255) NOT NULL,
  `entity_type` VARCHAR(255),
  `entity_id` VARCHAR(64),
  `message` VARCHAR(255),
  `raw_data` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `import_jobs` (
  `id` VARCHAR(64) NOT NULL,
  `import_type` VARCHAR(255) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `source_object_key` VARCHAR(255),
  `status` VARCHAR(64) NOT NULL DEFAULT 'uploaded',
  `rows_total` BIGINT NOT NULL DEFAULT 0,
  `rows_to_create` INT NOT NULL DEFAULT 0,
  `rows_to_update` INT NOT NULL DEFAULT 0,
  `rows_unchanged` INT NOT NULL DEFAULT 0,
  `rows_with_warnings` INT NOT NULL DEFAULT 0,
  `rows_with_errors` INT NOT NULL DEFAULT 0,
  `created_by` VARCHAR(255) NOT NULL,
  `confirmed_by` VARCHAR(255),
  `confirmed_at` BIGINT,
  `completed_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `outbox_events` (
  `id` VARCHAR(64) NOT NULL,
  `event_type` VARCHAR(255) NOT NULL,
  `aggregate_type` VARCHAR(64) NOT NULL,
  `aggregate_id` VARCHAR(64) NOT NULL,
  `payload` MEDIUMTEXT NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `attempts` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(255),
  `next_attempt_at` BIGINT,
  `delivered_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `scheduled_job_runs` (
  `id` VARCHAR(64) NOT NULL,
  `job_name` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `started_at` BIGINT NOT NULL,
  `finished_at` BIGINT,
  `items_processed` INT NOT NULL DEFAULT 0,
  `error` VARCHAR(255),
  `summary` VARCHAR(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `system_settings` (
  `id` VARCHAR(64) NOT NULL,
  `key` VARCHAR(64) NOT NULL,
  `value` TEXT NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bootstrap_attempts` (
  `id` VARCHAR(64) NOT NULL,
  `ip_hash` VARCHAR(255),
  `outcome` VARCHAR(255) NOT NULL,
  `attempted_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `installation_state` (
  `id` VARCHAR(64) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `claimed_at` BIGINT NOT NULL,
  `completed_at` BIGINT,
  `completed_by_user_id` VARCHAR(64),
  `token_consumed_at` BIGINT,
  PRIMARY KEY (`id`),
  CONSTRAINT `installation_state_singleton` CHECK (`id` = 'singleton'),
  CONSTRAINT `installation_state_status` CHECK (`status` IN ('in_progress','completed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `staff_invitations` (
  `id` VARCHAR(64) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role_ids` VARCHAR(255) NOT NULL,
  `invited_by` VARCHAR(255) NOT NULL,
  `token_hash` VARCHAR(128) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `expires_at` BIGINT NOT NULL,
  `accepted_at` BIGINT,
  `accepted_by_user_id` VARCHAR(64),
  `revoked_at` BIGINT,
  `revoked_by` VARCHAR(255),
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_search_map` (
  `rowid` INT,
  `product_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`rowid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_reviews` (
  `id` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(64) NOT NULL,
  `order_item_id` VARCHAR(64),
  `provenance` VARCHAR(255) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT 'pending',
  `author_name` VARCHAR(255) NOT NULL,
  `rating` INT NOT NULL,
  `title` VARCHAR(255),
  `body` MEDIUMTEXT NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `moderated_by` VARCHAR(255),
  `moderated_at` BIGINT,
  `moderation_note` VARCHAR(255),
  `published_at` BIGINT,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_reviews_rating_range` CHECK (`rating` BETWEEN 1 AND 5),
  CONSTRAINT `product_reviews_provenance` CHECK (`provenance` IN ('verified_purchase', 'in_store')),
  CONSTRAINT `product_reviews_verified_needs_order` CHECK (`provenance` <> 'verified_purchase' OR `order_item_id` IS NOT NULL),
  CONSTRAINT `product_reviews_status` CHECK (`status` IN ('pending', 'published', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Indexes ─────────────────────────────────────────────────────────────
CREATE INDEX `account_user_idx` ON `account` (`user_id`);
CREATE UNIQUE INDEX `permissions_code_unique` ON `permissions` (`code`);
CREATE UNIQUE INDEX `role_permissions_unique` ON `role_permissions` (`role_id`, `permission_id`);
CREATE UNIQUE INDEX `roles_code_unique` ON `roles` (`code`);
CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);
CREATE INDEX `session_user_idx` ON `session` (`user_id`);
CREATE UNIQUE INDEX `staff_profiles_user_unique` ON `staff_profiles` (`user_id`);
CREATE INDEX `step_up_user_purpose_idx` ON `step_up_sessions` (`user_id`, `purpose`, `expires_at`);
CREATE INDEX `two_factor_user_idx` ON `two_factor` (`user_id`);
CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);
CREATE UNIQUE INDEX `user_roles_unique` ON `user_roles` (`user_id`, `role_id`);
CREATE INDEX `user_roles_user_idx` ON `user_roles` (`user_id`);
CREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);
CREATE UNIQUE INDEX `brand_translations_unique` ON `brand_translations` (`brand_id`, `locale`);
CREATE UNIQUE INDEX `brands_slug_unique` ON `brands` (`slug`);
CREATE UNIQUE INDEX `categories_slug_unique` ON `categories` (`slug`);
CREATE INDEX `categories_parent_idx` ON `categories` (`parent_id`);
CREATE INDEX `categories_path_idx` ON `categories` (`path`);
CREATE UNIQUE INDEX `category_translations_unique` ON `category_translations` (`category_id`, `locale`);
CREATE UNIQUE INDEX `product_category_assignments_unique` ON `product_category_assignments` (`product_id`, `category_id`);
CREATE INDEX `product_category_category_idx` ON `product_category_assignments` (`category_id`);
CREATE INDEX `product_images_product_idx` ON `product_images` (`product_id`, `sort_order`);
CREATE INDEX `product_images_variant_idx` ON `product_images` (`variant_id`);
CREATE UNIQUE INDEX `product_relationships_unique` ON `product_relationships` (`product_id`, `related_product_id`, `relationship_type`);
CREATE UNIQUE INDEX `product_safety_product_unique` ON `product_safety_information` (`product_id`);
CREATE INDEX `product_specifications_product_idx` ON `product_specifications` (`product_id`);
CREATE UNIQUE INDEX `product_translations_unique` ON `product_translations` (`product_id`, `locale`);
CREATE UNIQUE INDEX `product_variants_sku_unique` ON `product_variants` (`sku`);
CREATE UNIQUE INDEX `product_variants_barcode_unique` ON `product_variants` (`barcode`);
CREATE INDEX `product_variants_product_idx` ON `product_variants` (`product_id`);
CREATE UNIQUE INDEX `products_slug_unique` ON `products` (`slug`);
CREATE INDEX `products_status_idx` ON `products` (`status`, `archived_at`);
CREATE INDEX `products_brand_idx` ON `products` (`brand_id`);
CREATE INDEX `products_family_idx` ON `products` (`product_family_id`);
CREATE UNIQUE INDEX `variant_option_assignments_unique` ON `variant_option_assignments` (`variant_id`, `option_value_id`);
CREATE UNIQUE INDEX `variant_option_groups_unique` ON `variant_option_groups` (`product_id`, `code`);
CREATE UNIQUE INDEX `variant_option_values_unique` ON `variant_option_values` (`group_id`, `value`);
CREATE INDEX `compatibility_logs_compat_idx` ON `compatibility_verification_logs` (`compatibility_id`, `created_at`);
CREATE UNIQUE INDEX `device_aliases_unique` ON `device_aliases` (`device_model_id`, `alias_normalised`);
CREATE INDEX `device_aliases_lookup_idx` ON `device_aliases` (`alias_normalised`);
CREATE UNIQUE INDEX `device_brand_translations_unique` ON `device_brand_translations` (`device_brand_id`, `locale`);
CREATE UNIQUE INDEX `device_brands_handle_unique` ON `device_brands` (`handle`);
CREATE UNIQUE INDEX `device_families_handle_unique` ON `device_families` (`handle`);
CREATE INDEX `device_families_brand_idx` ON `device_families` (`device_brand_id`, `sort_order`);
CREATE UNIQUE INDEX `device_family_translations_unique` ON `device_family_translations` (`device_family_id`, `locale`);
CREATE UNIQUE INDEX `device_model_translations_unique` ON `device_model_translations` (`device_model_id`, `locale`);
CREATE UNIQUE INDEX `device_models_handle_unique` ON `device_models` (`handle`);
CREATE INDEX `device_models_family_idx` ON `device_models` (`device_family_id`, `sort_order`);
CREATE INDEX `device_models_brand_idx` ON `device_models` (`device_brand_id`);
CREATE INDEX `device_models_popular_idx` ON `device_models` (`is_popular`, `sort_order`);
CREATE INDEX `product_compatibility_device_idx` ON `product_compatibility` (`device_model_id`, `product_id`);
CREATE INDEX `product_compatibility_product_idx` ON `product_compatibility` (`product_id`);
CREATE UNIQUE INDEX `product_families_handle_unique` ON `product_families` (`handle`);
CREATE UNIQUE INDEX `product_family_members_unique` ON `product_family_members` (`product_family_id`, `product_id`);
CREATE INDEX `product_family_members_product_idx` ON `product_family_members` (`product_id`);
CREATE UNIQUE INDEX `coupon_redemptions_order_unique` ON `coupon_redemptions` (`coupon_id`, `order_id`);
CREATE INDEX `coupon_redemptions_customer_idx` ON `coupon_redemptions` (`coupon_id`, `customer_email`);
CREATE UNIQUE INDEX `coupons_code_unique` ON `coupons` (`code`);
CREATE INDEX `price_history_variant_idx` ON `price_history` (`variant_id`, `effective_from`);
CREATE UNIQUE INDEX `price_lists_code_unique` ON `price_lists` (`code`);
CREATE INDEX `promotion_products_promotion_idx` ON `promotion_products` (`promotion_id`);
CREATE UNIQUE INDEX `promotions_code_unique` ON `promotions` (`code`);
CREATE INDEX `promotions_window_idx` ON `promotions` (`active`, `starts_at`, `ends_at`);
CREATE UNIQUE INDEX `variant_prices_unique` ON `variant_prices` (`variant_id`, `price_list_id`);
CREATE INDEX `variant_prices_variant_idx` ON `variant_prices` (`variant_id`);
CREATE UNIQUE INDEX `inventory_levels_unique` ON `inventory_levels` (`variant_id`, `location_id`);
CREATE INDEX `inventory_levels_variant_idx` ON `inventory_levels` (`variant_id`);
CREATE UNIQUE INDEX `inventory_locations_code_unique` ON `inventory_locations` (`code`);
CREATE INDEX `stock_adjustments_variant_idx` ON `stock_adjustments` (`variant_id`, `created_at`);
CREATE INDEX `stock_movements_variant_idx` ON `stock_movements` (`variant_id`, `created_at`);
CREATE INDEX `stock_movements_reference_idx` ON `stock_movements` (`reference_type`, `reference_id`);
CREATE INDEX `stock_movements_location_idx` ON `stock_movements` (`location_id`, `created_at`);
CREATE INDEX `stock_reservations_sweep_idx` ON `stock_reservations` (`status`, `expires_at`);
CREATE INDEX `stock_reservations_order_idx` ON `stock_reservations` (`order_id`);
CREATE INDEX `stock_reservations_variant_idx` ON `stock_reservations` (`variant_id`, `status`);
CREATE INDEX `stock_transfer_items_transfer_idx` ON `stock_transfer_items` (`transfer_id`);
CREATE UNIQUE INDEX `stock_transfers_reference_unique` ON `stock_transfers` (`reference`);
CREATE UNIQUE INDEX `cart_items_unique` ON `cart_items` (`cart_id`, `variant_id`);
CREATE INDEX `cart_items_cart_idx` ON `cart_items` (`cart_id`);
CREATE UNIQUE INDEX `carts_token_unique` ON `carts` (`token`);
CREATE INDEX `carts_user_idx` ON `carts` (`user_id`);
CREATE INDEX `carts_expiry_idx` ON `carts` (`expires_at`);
CREATE UNIQUE INDEX `order_addresses_unique` ON `order_addresses` (`order_id`, `address_type`);
CREATE INDEX `order_events_order_idx` ON `order_events` (`order_id`, `created_at`);
CREATE INDEX `order_items_order_idx` ON `order_items` (`order_id`);
CREATE INDEX `order_notes_order_idx` ON `order_notes` (`order_id`, `customer_visible`);
CREATE INDEX `order_status_history_order_idx` ON `order_status_history` (`order_id`, `created_at`);
CREATE UNIQUE INDEX `orders_number_unique` ON `orders` (`order_number`);
CREATE UNIQUE INDEX `orders_tracking_token_unique` ON `orders` (`tracking_token`);
CREATE INDEX `orders_status_idx` ON `orders` (`status`, `created_at`);
CREATE INDEX `orders_email_idx` ON `orders` (`customer_email`);
CREATE INDEX `orders_user_idx` ON `orders` (`user_id`);
CREATE INDEX `orders_reservation_idx` ON `orders` (`reservation_expires_at`);
CREATE INDEX `order_payments_order_idx` ON `order_payments` (`order_id`);
CREATE INDEX `order_payments_status_idx` ON `order_payments` (`status`, `created_at`);
CREATE INDEX `order_payments_reference_idx` ON `order_payments` (`transaction_reference`);
CREATE UNIQUE INDEX `payment_methods_code_unique` ON `payment_methods` (`code`);
CREATE INDEX `payment_proof_access_proof_idx` ON `payment_proof_access_logs` (`proof_id`, `accessed_at`);
CREATE INDEX `payment_proofs_payment_idx` ON `payment_proofs` (`order_payment_id`);
CREATE INDEX `payment_status_history_payment_idx` ON `payment_status_history` (`order_payment_id`, `created_at`);
CREATE UNIQUE INDEX `fulfilment_items_unique` ON `fulfilment_items` (`fulfilment_id`, `order_item_id`);
CREATE INDEX `fulfilment_status_history_idx` ON `fulfilment_status_history` (`fulfilment_id`, `created_at`);
CREATE INDEX `fulfilments_order_idx` ON `fulfilments` (`order_id`);
CREATE INDEX `fulfilments_status_idx` ON `fulfilments` (`status`);
CREATE UNIQUE INDEX `pickup_orders_order_unique` ON `pickup_orders` (`order_id`);
CREATE INDEX `refund_items_refund_idx` ON `refund_items` (`refund_id`);
CREATE INDEX `refunds_order_idx` ON `refunds` (`order_id`);
CREATE INDEX `return_items_request_idx` ON `return_items` (`return_request_id`);
CREATE UNIQUE INDEX `return_requests_reference_unique` ON `return_requests` (`reference`);
CREATE INDEX `return_requests_order_idx` ON `return_requests` (`order_id`);
CREATE INDEX `return_requests_status_idx` ON `return_requests` (`status`, `requested_at`);
CREATE INDEX `shipments_fulfilment_idx` ON `shipments` (`fulfilment_id`);
CREATE UNIQUE INDEX `shipping_methods_code_unique` ON `shipping_methods` (`code`);
CREATE UNIQUE INDEX `shipping_rates_unique` ON `shipping_rates` (`shipping_method_id`, `shipping_zone_id`);
CREATE UNIQUE INDEX `shipping_zones_code_unique` ON `shipping_zones` (`code`);
CREATE INDEX `banners_placement_idx` ON `banners` (`placement`, `active`);
CREATE UNIQUE INDEX `homepage_section_translations_unique` ON `homepage_section_translations` (`section_id`, `locale`);
CREATE INDEX `homepage_sections_order_idx` ON `homepage_sections` (`sort_order`);
CREATE UNIQUE INDEX `legal_document_versions_unique` ON `legal_document_versions` (`document_id`, `version`);
CREATE INDEX `legal_document_versions_effective_idx` ON `legal_document_versions` (`document_id`, `effective_from`);
CREATE UNIQUE INDEX `legal_documents_code_unique` ON `legal_documents` (`code`);
CREATE INDEX `navigation_items_menu_idx` ON `navigation_items` (`menu_id`, `sort_order`);
CREATE INDEX `navigation_items_parent_idx` ON `navigation_items` (`parent_id`);
CREATE UNIQUE INDEX `navigation_menus_code_unique` ON `navigation_menus` (`code`);
CREATE UNIQUE INDEX `page_translations_unique` ON `page_translations` (`page_id`, `locale`);
CREATE UNIQUE INDEX `pages_slug_unique` ON `pages` (`slug`);
CREATE INDEX `pages_status_idx` ON `pages` (`status`, `publish_at`);
CREATE UNIQUE INDEX `store_settings_key_unique` ON `store_settings` (`key`);
CREATE INDEX `store_settings_category_idx` ON `store_settings` (`category`);
CREATE INDEX `audit_logs_entity_idx` ON `audit_logs` (`entity_type`, `entity_id`, `created_at`);
CREATE INDEX `audit_logs_actor_idx` ON `audit_logs` (`actor_id`, `created_at`);
CREATE INDEX `audit_logs_action_idx` ON `audit_logs` (`action`, `created_at`);
CREATE INDEX `email_logs_recipient_idx` ON `email_logs` (`recipient`, `created_at`);
CREATE INDEX `email_logs_status_idx` ON `email_logs` (`status`, `created_at`);
CREATE INDEX `export_jobs_status_idx` ON `export_jobs` (`status`, `created_at`);
CREATE UNIQUE INDEX `feature_flags_key_unique` ON `feature_flags` (`key`);
CREATE UNIQUE INDEX `idempotency_keys_unique` ON `idempotency_keys` (`key`, `scope`);
CREATE INDEX `idempotency_keys_expiry_idx` ON `idempotency_keys` (`expires_at`);
CREATE INDEX `import_job_rows_job_idx` ON `import_job_rows` (`import_job_id`, `row_number`);
CREATE INDEX `import_jobs_status_idx` ON `import_jobs` (`status`, `created_at`);
CREATE INDEX `outbox_events_pending_idx` ON `outbox_events` (`status`, `next_attempt_at`);
CREATE INDEX `outbox_events_aggregate_idx` ON `outbox_events` (`aggregate_type`, `aggregate_id`);
CREATE INDEX `scheduled_job_runs_job_idx` ON `scheduled_job_runs` (`job_name`, `started_at`);
CREATE UNIQUE INDEX `system_settings_key_unique` ON `system_settings` (`key`);
CREATE INDEX `bootstrap_attempts_recent_idx` ON `bootstrap_attempts` (`attempted_at`);
CREATE UNIQUE INDEX `staff_invitations_token_unique` ON `staff_invitations` (`token_hash`);
CREATE INDEX `staff_invitations_email_idx` ON `staff_invitations` (`email`, `status`);
CREATE INDEX `staff_invitations_status_idx` ON `staff_invitations` (`status`, `expires_at`);
CREATE INDEX `account_issuer_idx` ON `account` (`issuer`, `account_id`);
CREATE UNIQUE INDEX `product_search_map_product` ON `product_search_map` (`product_id`);
CREATE INDEX `product_reviews_product_idx` ON `product_reviews` (`product_id`, `status`);
CREATE INDEX `product_reviews_status_idx` ON `product_reviews` (`status`, `created_at`);
CREATE UNIQUE INDEX `product_specifications_scope_unique` ON `product_specifications` (`product_id`, `variant_scope`, `spec_key`);
CREATE UNIQUE INDEX `product_compatibility_scope_unique` ON `product_compatibility` (`product_id`, `variant_scope`, `device_model_id`);

-- ── Foreign keys ────────────────────────────────────────────────────────
ALTER TABLE `account` ADD CONSTRAINT `fk_account_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `role_permissions` ADD CONSTRAINT `fk_role_permissions_role_id_0` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `role_permissions` ADD CONSTRAINT `fk_role_permissions_permission_id_1` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `session` ADD CONSTRAINT `fk_session_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `staff_profiles` ADD CONSTRAINT `fk_staff_profiles_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `step_up_sessions` ADD CONSTRAINT `fk_step_up_sessions_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `two_factor` ADD CONSTRAINT `fk_two_factor_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_user_id_0` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_role_id_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_granted_by_2` FOREIGN KEY (`granted_by`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `brand_translations` ADD CONSTRAINT `fk_brand_translations_brand_id_0` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `category_translations` ADD CONSTRAINT `fk_category_translations_category_id_0` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_category_assignments` ADD CONSTRAINT `fk_product_category_assignments_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_category_assignments` ADD CONSTRAINT `fk_product_category_assignments_category_id_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `product_images` ADD CONSTRAINT `fk_product_images_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_images` ADD CONSTRAINT `fk_product_images_variant_id_1` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `product_relationships` ADD CONSTRAINT `fk_product_relationships_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_relationships` ADD CONSTRAINT `fk_product_relationships_related_product_id_1` FOREIGN KEY (`related_product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_safety_information` ADD CONSTRAINT `fk_product_safety_information_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_specifications` ADD CONSTRAINT `fk_product_specifications_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_specifications` ADD CONSTRAINT `fk_product_specifications_variant_id_1` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_translations` ADD CONSTRAINT `fk_product_translations_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_variants` ADD CONSTRAINT `fk_product_variants_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `products` ADD CONSTRAINT `fk_products_brand_id_0` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `products` ADD CONSTRAINT `fk_products_primary_category_id_1` FOREIGN KEY (`primary_category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `variant_option_assignments` ADD CONSTRAINT `fk_variant_option_assignments_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `variant_option_assignments` ADD CONSTRAINT `fk_variant_option_assignments_option_value_id_1` FOREIGN KEY (`option_value_id`) REFERENCES `variant_option_values` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `variant_option_groups` ADD CONSTRAINT `fk_variant_option_groups_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `variant_option_values` ADD CONSTRAINT `fk_variant_option_values_group_id_0` FOREIGN KEY (`group_id`) REFERENCES `variant_option_groups` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `compatibility_verification_logs` ADD CONSTRAINT `fk_compatibility_verification_logs_compatibility_id_0` FOREIGN KEY (`compatibility_id`) REFERENCES `product_compatibility` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `device_aliases` ADD CONSTRAINT `fk_device_aliases_device_model_id_0` FOREIGN KEY (`device_model_id`) REFERENCES `device_models` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `device_brand_translations` ADD CONSTRAINT `fk_device_brand_translations_device_brand_id_0` FOREIGN KEY (`device_brand_id`) REFERENCES `device_brands` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `device_families` ADD CONSTRAINT `fk_device_families_device_brand_id_0` FOREIGN KEY (`device_brand_id`) REFERENCES `device_brands` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `device_family_translations` ADD CONSTRAINT `fk_device_family_translations_device_family_id_0` FOREIGN KEY (`device_family_id`) REFERENCES `device_families` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `device_model_translations` ADD CONSTRAINT `fk_device_model_translations_device_model_id_0` FOREIGN KEY (`device_model_id`) REFERENCES `device_models` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `device_models` ADD CONSTRAINT `fk_device_models_device_brand_id_0` FOREIGN KEY (`device_brand_id`) REFERENCES `device_brands` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `device_models` ADD CONSTRAINT `fk_device_models_device_family_id_1` FOREIGN KEY (`device_family_id`) REFERENCES `device_families` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `product_compatibility` ADD CONSTRAINT `fk_product_compatibility_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_compatibility` ADD CONSTRAINT `fk_product_compatibility_variant_id_1` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_compatibility` ADD CONSTRAINT `fk_product_compatibility_device_model_id_2` FOREIGN KEY (`device_model_id`) REFERENCES `device_models` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `product_family_members` ADD CONSTRAINT `fk_product_family_members_product_family_id_0` FOREIGN KEY (`product_family_id`) REFERENCES `product_families` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_family_members` ADD CONSTRAINT `fk_product_family_members_product_id_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `coupon_redemptions` ADD CONSTRAINT `fk_coupon_redemptions_coupon_id_0` FOREIGN KEY (`coupon_id`) REFERENCES `coupons` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `price_history` ADD CONSTRAINT `fk_price_history_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `price_history` ADD CONSTRAINT `fk_price_history_price_list_id_1` FOREIGN KEY (`price_list_id`) REFERENCES `price_lists` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `promotion_products` ADD CONSTRAINT `fk_promotion_products_promotion_id_0` FOREIGN KEY (`promotion_id`) REFERENCES `promotions` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `promotion_products` ADD CONSTRAINT `fk_promotion_products_product_id_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `promotion_products` ADD CONSTRAINT `fk_promotion_products_variant_id_2` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `variant_prices` ADD CONSTRAINT `fk_variant_prices_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `variant_prices` ADD CONSTRAINT `fk_variant_prices_price_list_id_1` FOREIGN KEY (`price_list_id`) REFERENCES `price_lists` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `inventory_levels` ADD CONSTRAINT `fk_inventory_levels_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `inventory_levels` ADD CONSTRAINT `fk_inventory_levels_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_movement_id_2` FOREIGN KEY (`movement_id`) REFERENCES `stock_movements` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `stock_movements` ADD CONSTRAINT `fk_stock_movements_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_movements` ADD CONSTRAINT `fk_stock_movements_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_reservations` ADD CONSTRAINT `fk_stock_reservations_variant_id_0` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_reservations` ADD CONSTRAINT `fk_stock_reservations_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_transfer_items` ADD CONSTRAINT `fk_stock_transfer_items_transfer_id_0` FOREIGN KEY (`transfer_id`) REFERENCES `stock_transfers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `stock_transfer_items` ADD CONSTRAINT `fk_stock_transfer_items_variant_id_1` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_from_location_id_0` FOREIGN KEY (`from_location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_to_location_id_1` FOREIGN KEY (`to_location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `cart_items` ADD CONSTRAINT `fk_cart_items_cart_id_0` FOREIGN KEY (`cart_id`) REFERENCES `carts` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `cart_items` ADD CONSTRAINT `fk_cart_items_variant_id_1` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `carts` ADD CONSTRAINT `fk_carts_device_model_id_0` FOREIGN KEY (`device_model_id`) REFERENCES `device_models` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `order_addresses` ADD CONSTRAINT `fk_order_addresses_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `order_events` ADD CONSTRAINT `fk_order_events_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_product_id_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_variant_id_2` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `order_notes` ADD CONSTRAINT `fk_order_notes_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `order_status_history` ADD CONSTRAINT `fk_order_status_history_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `orders` ADD CONSTRAINT `fk_orders_device_model_id_0` FOREIGN KEY (`device_model_id`) REFERENCES `device_models` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `order_payments` ADD CONSTRAINT `fk_order_payments_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `order_payments` ADD CONSTRAINT `fk_order_payments_payment_method_id_1` FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `payment_proof_access_logs` ADD CONSTRAINT `fk_payment_proof_access_logs_proof_id_0` FOREIGN KEY (`proof_id`) REFERENCES `payment_proofs` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `payment_proofs` ADD CONSTRAINT `fk_payment_proofs_order_payment_id_0` FOREIGN KEY (`order_payment_id`) REFERENCES `order_payments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `payment_status_history` ADD CONSTRAINT `fk_payment_status_history_order_payment_id_0` FOREIGN KEY (`order_payment_id`) REFERENCES `order_payments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `fulfilment_items` ADD CONSTRAINT `fk_fulfilment_items_fulfilment_id_0` FOREIGN KEY (`fulfilment_id`) REFERENCES `fulfilments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `fulfilment_items` ADD CONSTRAINT `fk_fulfilment_items_order_item_id_1` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `fulfilment_status_history` ADD CONSTRAINT `fk_fulfilment_status_history_fulfilment_id_0` FOREIGN KEY (`fulfilment_id`) REFERENCES `fulfilments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `fulfilments` ADD CONSTRAINT `fk_fulfilments_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `fulfilments` ADD CONSTRAINT `fk_fulfilments_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `pickup_orders` ADD CONSTRAINT `fk_pickup_orders_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `pickup_orders` ADD CONSTRAINT `fk_pickup_orders_location_id_1` FOREIGN KEY (`location_id`) REFERENCES `inventory_locations` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `refund_items` ADD CONSTRAINT `fk_refund_items_refund_id_0` FOREIGN KEY (`refund_id`) REFERENCES `refunds` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `refund_items` ADD CONSTRAINT `fk_refund_items_order_item_id_1` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `refunds` ADD CONSTRAINT `fk_refunds_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `refunds` ADD CONSTRAINT `fk_refunds_return_request_id_1` FOREIGN KEY (`return_request_id`) REFERENCES `return_requests` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `return_items` ADD CONSTRAINT `fk_return_items_return_request_id_0` FOREIGN KEY (`return_request_id`) REFERENCES `return_requests` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `return_items` ADD CONSTRAINT `fk_return_items_order_item_id_1` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `return_requests` ADD CONSTRAINT `fk_return_requests_order_id_0` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `shipments` ADD CONSTRAINT `fk_shipments_fulfilment_id_0` FOREIGN KEY (`fulfilment_id`) REFERENCES `fulfilments` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `shipping_rates` ADD CONSTRAINT `fk_shipping_rates_shipping_method_id_0` FOREIGN KEY (`shipping_method_id`) REFERENCES `shipping_methods` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `shipping_rates` ADD CONSTRAINT `fk_shipping_rates_shipping_zone_id_1` FOREIGN KEY (`shipping_zone_id`) REFERENCES `shipping_zones` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `homepage_section_translations` ADD CONSTRAINT `fk_homepage_section_translations_section_id_0` FOREIGN KEY (`section_id`) REFERENCES `homepage_sections` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `legal_document_versions` ADD CONSTRAINT `fk_legal_document_versions_document_id_0` FOREIGN KEY (`document_id`) REFERENCES `legal_documents` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `navigation_items` ADD CONSTRAINT `fk_navigation_items_menu_id_0` FOREIGN KEY (`menu_id`) REFERENCES `navigation_menus` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `page_translations` ADD CONSTRAINT `fk_page_translations_page_id_0` FOREIGN KEY (`page_id`) REFERENCES `pages` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `email_logs` ADD CONSTRAINT `fk_email_logs_outbox_event_id_0` FOREIGN KEY (`outbox_event_id`) REFERENCES `outbox_events` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `import_job_rows` ADD CONSTRAINT `fk_import_job_rows_import_job_id_0` FOREIGN KEY (`import_job_id`) REFERENCES `import_jobs` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `staff_invitations` ADD CONSTRAINT `fk_staff_invitations_invited_by_0` FOREIGN KEY (`invited_by`) REFERENCES `user` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `product_search_map` ADD CONSTRAINT `fk_product_search_map_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_reviews` ADD CONSTRAINT `fk_product_reviews_product_id_0` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `product_reviews` ADD CONSTRAINT `fk_product_reviews_order_item_id_1` FOREIGN KEY (`order_item_id`) REFERENCES `order_items` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
