/**
 * Generates the MariaDB baseline schema from the applied D1 migrations.
 *
 * `node scripts/hostinger/generate-schema.mjs`
 *
 * The D1 migrations in db/migrations are NOT touched. They are the applied
 * history of the Cloudflare database and rewriting them would make the running
 * preview unreproducible. This reads them and writes a separate target schema
 * under db/mariadb/migrations, which is the only thing the MariaDB deployment
 * ever applies.
 *
 * Re-running is safe and is the point: when a D1 migration is added, this
 * regenerates, the diff is reviewable, and nothing drifts silently.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  splitStatements,
  parseCreateTable,
  parseCreateIndex,
  parseAlterTableAddColumn,
  classifyStatement,
} from "./lib/sqlite-ddl.mjs";
import { buildSchema, FTS_ARTEFACTS, SCOPE_REPLACEMENTS } from "./lib/emit-mariadb.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const sourceDir = path.join(root, "db/migrations");
const targetDir = path.join(root, "db/mariadb/migrations");

const files = fs
  .readdirSync(sourceDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

/** @type {Map<string, import("./lib/sqlite-ddl.mjs").Table>} */
const tables = new Map();
const indexes = [];
const ignored = [];

for (const file of files) {
  const sql = fs.readFileSync(path.join(sourceDir, file), "utf8");
  for (const statement of splitStatements(sql)) {
    const kind = classifyStatement(statement);

    switch (kind) {
      case "create_table": {
        const table = parseCreateTable(statement);
        if (!table) throw new Error(`${file}: CREATE TABLE did not parse:\n${statement}`);
        if (tables.has(table.name))
          throw new Error(`${file}: duplicate CREATE TABLE ${table.name}`);
        tables.set(table.name, table);
        break;
      }
      case "create_index": {
        const index = parseCreateIndex(statement);
        if (!index) throw new Error(`${file}: CREATE INDEX did not parse:\n${statement}`);
        indexes.push(index);
        break;
      }
      case "add_column": {
        const added = parseAlterTableAddColumn(statement);
        if (!added) throw new Error(`${file}: ALTER TABLE ADD COLUMN did not parse:\n${statement}`);
        const table = tables.get(added.table);
        if (!table) throw new Error(`${file}: ALTER TABLE on unknown table ${added.table}`);
        table.columns.push(added.column);
        break;
      }
      // Statements with no place in a baseline schema. Each is recorded rather
      // than skipped quietly, and the count is printed: a migration that starts
      // doing something new should show up here as a surprise.
      case "create_virtual_table":
      case "create_trigger":
      case "insert":
      case "update":
      case "delete":
      case "drop":
      case "pragma":
        ignored.push({ file, kind, head: statement.slice(0, 70).replace(/\s+/g, " ") });
        break;
      default:
        throw new Error(`${file}: unclassified statement:\n${statement.slice(0, 300)}`);
    }
  }
}

const model = { tables: [...tables.values()], indexes };
const { statements, foreignKeyStatements, indexStatements, decisions, skippedIndexes } =
  buildSchema(model);

const header = `-- MariaDB baseline schema for Covers by Mobile Zam Zam.
--
-- GENERATED by scripts/hostinger/generate-schema.mjs from db/migrations.
-- Do not hand-edit: regenerate, review the diff, and commit.
--
-- Source D1 migrations : ${files.join(", ")}
-- Tables               : ${statements.length}
-- Indexes              : ${indexStatements.length}
-- Foreign keys         : ${foreignKeyStatements.length}
--
-- Two departures from a literal translation, both deliberate:
--
--   * ${skippedIndexes.length} SQLite partial unique indexes have no MariaDB equivalent and are
--     replaced by generated scope columns with an ordinary UNIQUE index over
--     them. See scripts/hostinger/lib/emit-mariadb.mjs for why a plain nullable
--     composite UNIQUE would enforce nothing.
--       ${skippedIndexes.map((i) => i.name).join("\n--       ")}
--
--   * The FTS5 virtual table and its triggers are not translated. Search is a
--     materialised document table with a FULLTEXT index; see 0002_search.sql.
--
-- Every table is InnoDB and utf8mb4. Timestamps are epoch milliseconds in
-- BIGINT, stored UTC, displayed Europe/Rome by the application — the database
-- holds no timezone and no DATETIME, exactly as D1 did.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;
`;

fs.mkdirSync(targetDir, { recursive: true });
fs.writeFileSync(
  path.join(targetDir, "0001_baseline.sql"),
  [
    header,
    "\n-- ── Tables ──────────────────────────────────────────────────────────────\n",
    statements.join("\n\n"),
    "\n\n-- ── Indexes ─────────────────────────────────────────────────────────────\n",
    indexStatements.join("\n"),
    "\n\n-- ── Foreign keys ────────────────────────────────────────────────────────\n",
    foreignKeyStatements.join("\n"),
    "\n",
  ].join(""),
  "utf8",
);

fs.writeFileSync(
  path.join(targetDir, "schema-decisions.json"),
  JSON.stringify({ generatedFrom: files, decisions, skippedIndexes, ignored }, null, 2),
  "utf8",
);

const byRule = decisions.reduce((acc, d) => {
  acc[d.rule] = (acc[d.rule] ?? 0) + 1;
  return acc;
}, {});

console.log(`Read ${files.length} D1 migrations.`);
console.log(`  tables        ${statements.length}`);
console.log(`  indexes       ${indexStatements.length}`);
console.log(`  foreign keys  ${foreignKeyStatements.length}`);
console.log(`  columns       ${decisions.length}`);
console.log(
  `  scope columns ${Object.keys(SCOPE_REPLACEMENTS).length} replacing ${skippedIndexes.length} partial indexes`,
);
console.log(`  FTS artefacts dropped: ${[...FTS_ARTEFACTS].join(", ")}`);
console.log("\nType rules applied:");
for (const [rule, count] of Object.entries(byRule).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${String(count).padStart(4)}  ${rule}`);
}
console.log(`\nNot carried into the baseline (${ignored.length} statements):`);
for (const item of ignored) console.log(`  ${item.file}  ${item.kind}  ${item.head}`);
console.log(`\nWrote db/mariadb/migrations/0001_baseline.sql`);
